### ISSUE TITLE
Peer Review - Ambiguity in some sections

### ISSUE THREAD

**Issue by fondsonlu** [OKKM-insights/OKKM.insights#119]
SRS DOCUMENT

Team 10 reviewing Team 11

Under section 1.2 'Goals of the Project' -> 'High Data Accuracy', I'm finding that this section utilizes the words 'classification accuracy of objects identified in the images'. I feel like this isn't very clear to the reader because it doesn't specify what sort of threshold of accuracy would be considered successful. It can be fairly ambiguous for the readers/stakeholders to really understand and assess the effectiveness of your online platform that brings simplicity to satellite imagery data analysis. I think being a bit more descriptive especially in the 'Goals' section, would highly benefit the readers, so they understand exactly what to expect. I think without a clear definition of success metrics, it can further lead to misalignment between development goals and user satisfaction. As a suggestion(if possible), maybe clarify what level of classification accuracy the system should achieve to meet project goals(i.e, a performance range, or target accuracy -> "95% classification accuracy").

**Comment by angelaw7** [comment]
Team 10 TA: @Necried
