### ISSUE TITLE
Peer Review - SRS Modification of Project Goals

### ISSUE THREAD

**Issue by paytonchan** [OKKM-insights/OKKM.insights#132]
**Artifact Under Review**
SRS

**Team Number for Team Doing the Review**
Team 10 reviewing Team 11

**Description of Issue**
In Section 1.2 under the heading "Results Returned Within Appropriate Timeframe", I think that this section could simply just be a constraint as there are similar descriptions in some of the Performance Requirements (Section 12). I believe that as the project progresses, these thresholds and constraints will inevitably be slightly modified to more accurately fit your final design.

**Comment by paytonchan** [comment]
Team 10 TA: @Necried

**Comment by KyleJMcMaster** [comment]
We believe this goal is important to convey the high level timing expectations to the user, before entering the details of the system
