### ISSUE TITLE
Peer Review [V&V] - nit: 3.1 team roles clarity

### ISSUE THREAD

**Issue by angelaw7** [OKKM-insights/OKKM.insights#200]
**Artifact Under Review**
V&V Plan

**Team Number for Team Doing the Review**
Team 10

**Description of Issue**
I like the idea of a table - I think for additional clarity you could split the responsibilities table into 2 columns for primary and secondary role

**Comment by KyleJMcMaster** [comment]
Thanks for the comment, but we feel that the table is currently readable and the proposed changes may not work well with other roles outside of the core team
